name: Deploy to Google Cloud Run

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: us-central1
  SERVICE_NAME: alteryx-swag-portal

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Debug GCP_SA_KEY
      run: |
        echo "Checking GCP_SA_KEY length:"
        echo "${{ secrets.GCP_SA_KEY }}" | wc -c
        echo "First 100 characters:"
        echo "${{ secrets.GCP_SA_KEY }}" | head -c 100
        echo "Last 100 characters:"
        echo "${{ secrets.GCP_SA_KEY }}" | tail -c 100
    
    - name: Google Auth (with error handling)
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
      continue-on-error: true
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
    
    - name: Configure gcloud
      run: |
        gcloud config set project ${{ env.PROJECT_ID }}
        gcloud config set run/region ${{ env.REGION }}
    
    - name: Try deployment without auth
      run: |
        echo "Attempting deployment..."
        gcloud run deploy ${{ env.SERVICE_NAME }} \
          --source . \
          --platform managed \
          --region ${{ env.REGION }} \
          --allow-unauthenticated \
          --memory 512Mi \
          --cpu 1 \
          --max-instances 10
      continue-on-error: true
    
    - name: Check deployment status
      run: |
        echo "Checking deployment status..."
        gcloud run services list --region=${{ env.REGION }}
