name: Deploy to Google Cloud Run

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: us-central1
  SERVICE_NAME: alteryx-swag-portal

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Debug environment
      run: |
        echo "Node version:"
        node --version
        echo "NPM version:"
        npm --version
        echo "Current directory:"
        pwd
        echo "Directory contents:"
        ls -la
    
    - name: Install dependencies
      run: npm ci
    
    - name: Debug after install
      run: |
        echo "Node modules installed:"
        ls -la node_modules | head -10
        echo "Package.json contents:"
        cat package.json
    
    - name: Build application
      run: |
        echo "Starting build..."
        npm run build
        echo "Build completed successfully"
    
    - name: Debug after build
      run: |
        echo "Build output:"
        ls -la .next
        echo "Standalone output:"
        ls -la .next/standalone || echo "No standalone output found"
    
    - name: Google Auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
    
    - name: Configure gcloud
      run: |
        echo "Setting project to: ${{ env.PROJECT_ID }}"
        gcloud config set project ${{ env.PROJECT_ID }}
        echo "Setting region to: ${{ env.REGION }}"
        gcloud config set run/region ${{ env.REGION }}
        echo "Current gcloud config:"
        gcloud config list
    
    - name: Check Cloud Run services
      run: |
        echo "Listing existing Cloud Run services:"
        gcloud run services list --region=${{ env.REGION }}
    
    - name: Enable required APIs
      run: |
        echo "Enabling required Google Cloud APIs..."
        gcloud services enable cloudbuild.googleapis.com
        gcloud services enable run.googleapis.com
        gcloud services enable containerregistry.googleapis.com
        echo "APIs enabled successfully"
    
    - name: Deploy to Cloud Run
      run: |
        echo "Starting deployment to Cloud Run..."
        echo "Service name: ${{ env.SERVICE_NAME }}"
        echo "Region: ${{ env.REGION }}"
        echo "Project: ${{ env.PROJECT_ID }}"
        
        # Deploy without environment variables first
        gcloud run deploy ${{ env.SERVICE_NAME }} \
          --source . \
          --platform managed \
          --region ${{ env.REGION }} \
          --allow-unauthenticated
    
    - name: Update environment variables
      run: |
        echo "Updating environment variables..."
        gcloud run services update ${{ env.SERVICE_NAME }} \
          --region ${{ env.REGION }} \
          --update-env-vars="SUPABASE_URL=${{ secrets.SUPABASE_URL }},NEXT_PUBLIC_SUPABASE_URL=${{ secrets.SUPABASE_URL }},SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }},NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }},SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_SERVICE_ROLE_KEY }},GOOGLE_MAPS_API_KEY=${{ secrets.GOOGLE_MAPS_API_KEY }},NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${{ secrets.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY }},NEXT_PUBLIC_APP_URL=${{ secrets.APP_URL }},SMTP_HOST=${{ secrets.SMTP_HOST }},SMTP_PORT=${{ secrets.SMTP_PORT }},SMTP_USER=${{ secrets.SMTP_USER }},SMTP_PASS=${{ secrets.SMTP_PASS }},FROM_EMAIL=${{ secrets.FROM_EMAIL }},WEBHOOK_SECRET=${{ secrets.WEBHOOK_SECRET }}"
    
    - name: Show service URL
      run: |
        echo "Getting service URL..."
        gcloud run services describe ${{ env.SERVICE_NAME }} \
          --platform managed \
          --region ${{ env.REGION }} \
          --format 'value(status.url)'
