name: Deploy to Google Cloud Run

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: us-central1
  SERVICE_NAME: alteryx-swag-portal

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Google Auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
    
    - name: Configure gcloud
      run: |
        gcloud config set project ${{ env.PROJECT_ID }}
        gcloud config set run/region ${{ env.REGION }}
        echo "Project: ${{ env.PROJECT_ID }}"
        echo "Region: ${{ env.REGION }}"
        echo "Service: ${{ env.SERVICE_NAME }}"
    
    - name: Check current services
      run: |
        echo "Current Cloud Run services:"
        gcloud run services list --region=${{ env.REGION }}
    
    - name: Try deployment with verbose logging
      run: |
        echo "Attempting deployment with verbose logging..."
        gcloud run deploy ${{ env.SERVICE_NAME }} \
          --source . \
          --platform managed \
          --region ${{ env.REGION }} \
          --allow-unauthenticated \
          --memory 512Mi \
          --cpu 1 \
          --max-instances 10 \
          --verbosity=debug
      continue-on-error: true
    
    - name: Check deployment status
      run: |
        echo "Checking deployment status..."
        gcloud run services list --region=${{ env.REGION }}
        echo "Service details:"
        gcloud run services describe ${{ env.SERVICE_NAME }} --region=${{ env.REGION }} || echo "Service not found"
